### ISSUE TITLE
Subtractive permission

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers-permissions#9]
### Feature Request

Allow subtracting permissions:
```js
[
  "users:*:*", // users
  "-:users:*:10" // except user with id 10
]
```

Added `-` at the front to indicate negative permission, but there must be a better way to do this.

**Comment by ekryski** [comment]
This is sort of like adding a blacklist. I don't think it's necessary because if the user is no longer allowed access then the revoked permissions should just be removed from their permissions array and if they don't have any in the first place then they won't be granted access.

I'm going to close this but we can re-open if I've missed something.
